name: febu
description: Fancy, yet basically useless extensions for dart language
version: 0.0.3
homepage: https://github.com/Code-Growers/febu

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
