name: grow_extensions
description: Fancy, yet basically useless extensions for dart language
version: 0.1.0
homepage: https://github.com/Code-Growers/grow_extensions

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  index_generator: 3.4.1

flutter:
  generate: true
